"""Create equipment, sensor reading and operating limit tables

Revision ID: b165fc3c8e2e
Revises: 
Create Date: 2026-10-02 01:51:57.426273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b165fc3c8e2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=32), nullable=False),
    sa.Column('equipment_type', sa.Enum('wet_christmas_tree', 'manifold', 'riser', 'bop', 'umbilical', 'plet', name='equipmenttype', native_enum=False, length=32), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('water_depth_m', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('operating', 'standby', 'maintenance', 'decommissioned', name='equipmentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('water_depth_m > 0', name='ck_equipment_positive_depth'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equipment_field_status', 'equipment', ['field_name', 'status'], unique=False)
    op.create_index(op.f('ix_equipment_tag'), 'equipment', ['tag'], unique=True)
    op.create_table('operating_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('sensor_type', sa.Enum('pressure', 'temperature', 'vibration', 'flow_rate', name='sensortype', native_enum=False, length=32), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.CheckConstraint('min_value < max_value', name='ck_limit_ordered_bounds'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_id', 'sensor_type', name='uq_limit_equipment_sensor')
    )
    op.create_index(op.f('ix_operating_limit_equipment_id'), 'operating_limit', ['equipment_id'], unique=False)
    op.create_table('sensor_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('sensor_type', sa.Enum('pressure', 'temperature', 'vibration', 'flow_rate', name='sensortype', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reading_equipment_sensor_time', 'sensor_reading', ['equipment_id', 'sensor_type', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_reading_equipment_id'), 'sensor_reading', ['equipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_reading_equipment_id'), table_name='sensor_reading')
    op.drop_index('ix_reading_equipment_sensor_time', table_name='sensor_reading')
    op.drop_table('sensor_reading')
    op.drop_index(op.f('ix_operating_limit_equipment_id'), table_name='operating_limit')
    op.drop_table('operating_limit')
    op.drop_index(op.f('ix_equipment_tag'), table_name='equipment')
    op.drop_index('ix_equipment_field_status', table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
